# Generated by Django 3.2.20 on 2023-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ablog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
