# Generated by Django 3.2.20 on 2023-07-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ablog', '0002_post_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heading',
        ),
    ]
