# Generated by Django 3.2.20 on 2023-08-09 06:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ablog', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
