# Generated by Django 3.2.20 on 2023-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ablog', '0008_auto_20230809_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Read More..', max_length=100),
        ),
    ]
