# Generated by Django 3.2.20 on 2023-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ablog', '0009_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
