# Generated by Django 3.2.20 on 2023-08-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ablog', '0011_auto_20230815_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
        ),
    ]
