# Generated by Django 3.2.20 on 2023-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ablog', '0013_auto_20230820_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
